# Generated by Django 2.0.9 on 2024-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDiSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField()),
                ('sub_start_time', models.CharField(max_length=6)),
                ('sub_end_time', models.CharField(max_length=6)),
                ('sub_email', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
