# Generated by Django 2.0.9 on 2024-05-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedisub',
            name='sub_end_time',
            field=models.DateTimeField(max_length=6),
        ),
        migrations.AlterField(
            model_name='changedisub',
            name='sub_start_time',
            field=models.DateTimeField(max_length=6),
        ),
    ]
